
services:
  # Ini service Database Graph kita
  neo4j:
    image: neo4j:latest  # Ambil image resmi terbaru
    container_name: graphweaver_db
    ports:
      - "7474:7474"  # Port buat buka Dashboard di Browser (HTTP)
      - "7687:7687"  # Port buat Python ngobrol sama DB (Bolt)
    environment:
      # Auth dimatikan dulu biar gampang belajar (Nanti di .env kalau mau aman)
      - NEO4J_AUTH=neo4j/badsfarmil232615
    volumes:
      # PENTING! Biar kalau Docker dimatiin, datanya GAK HILANG.
      - ./neo4j_data:/data
      - ./neo4j_logs:/logs
    restart: unless-stopped